apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-js
  template:
    metadata:
      labels:
        app: node-js
    spec:
      containers:
      - name: node-js
        image: 64m03412.c1.gra9.container-registry.ovh.net/staging_test_registry_7/node:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
      imagePullSecrets:
      - name: bgregistrykey
    data:
      .dockerconfigjson: {{ "{\"auths\": {\"https://7tiuxysa.c1.gra9.container-registry.ovh.net/\": {\"username\": \"UcfvXPtlbX\", \"password\": \"x93752H0jS4f618s\"}}}" | b64enc }}

---

apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: LoadBalancer
  selector:
    app: node-js
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP

