---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: 7tiuxysa.c1.gra9.container-registry.ovh.net/ymk/react:64
          resources:
            limits:
              memory: 356Mi
              cpu: 500m
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: harbor-login-secret
      data:
        .dockerconfigjson: {{ "{\"auths\": {\"https://7tiuxysa.c1.gra9.container-registry.ovh.net/\": {\"username\": \"UcfvXPtlbX\", \"password\": \"x93752H0jS4f618s\"}}}" | b64enc }}

---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: LoadBalancer
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
